apiVersion: v1
kind: Namespace
metadata:
  name: selenoid
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: selenoid
  name: selenoid-app
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: selenoid-app
  namespace: selenoid
roleRef:
  kind: Role
  name: selenoid-app
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: selenoid
  name: default
