apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-selenoid-images-prepull
  annotations:
    source: "selenoid-images-prepull images"
  labels:
    app: {{ .Release.Name }}-selenoid
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-selenoid-images-prepull
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-selenoid-images-prepull
    spec:
      containers:
      - name: pause
        image: {{ .Values.image.repositoryPause }}:{{ .Values.image.tagPause }}
      initContainers:
      - name: selenoid-images-prepull
        image: {{ .Values.image.repositoryPrepull }}:{{ .Values.image.tagPrepull }}
        command:
        - sh
        - -c
        - grep image /etc/selenoid/browsers.json | awk '{print $2}' | tr -d ',' | tr -d '"' |
          xargs -I{} docker pull {}
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        - name: browsers-config
          mountPath: /etc/selenoid
        securityContext:
          privileged: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run
      - name: browsers-config
        configMap:
          name: {{ .Release.Name }}-selenoid-config
    {{- if .Values.placement.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.placement.nodeSelector | indent 8 }}
    {{- end }}
